"""
[Partner B]
scripts/load_nsl_kdd_external.py

Downloads the NSL-KDD intrusion detection benchmark (the dataset your own
Phase 1 literature review names directly) and reshapes it to match the
7-feature schema your XGBoost model expects, so you can sanity-check the
model against a real, independent, open-source dataset rather than only
ever testing it against your own synthetic generator.

WHY THIS MATTERS: your synthetic_traffic.csv was generated by the same
logic your model is trained on, so near-perfect accuracy on it doesn't
prove much (see check_leakage.py). NSL-KDD is a completely independently
collected dataset, so testing against it is a much more honest check of
whether the model generalizes at all, or only memorized synthetic patterns.

SOURCE & LICENSE NOTE:
The dataset's original host (unb.ca/cic/datasets/nsl.html) currently shows
"this dataset is no longer available" at the canonical URL. This script
pulls from a long-standing, widely-forked GitHub mirror of the original
files instead (jmnwong/NSL-KDD-Dataset, 33 forks at time of writing).
NSL-KDD's license explicitly permits redistribution/mirroring provided the
source paper is cited (Tavallaee et al., 2009) -- that citation is included
in the saved stats JSON below.

FEATURE MAPPING (NSL-KDD's 41 flow-level features -> your 7 raw features):
NSL-KDD measures connection-level statistics (e.g. counts over a 2-second
window), not raw single-packet honeypot data, so this is a deliberate
approximation, not a 1:1 equivalence. Each mapping choice is commented
below. Treat this as "does my model behave sensibly on a structurally
similar but independently-sourced dataset", not as a perfect schema match.

Run:
    python scripts/load_nsl_kdd_external.py
    python scripts/load_nsl_kdd_external.py --subset 20percent   # faster, smaller
"""

import argparse
import json
import logging
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
import requests

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
logger = logging.getLogger("load_nsl_kdd_external")

GITHUB_MIRROR_BASE = "https://raw.githubusercontent.com/jmnwong/NSL-KDD-Dataset/master/"

FILES = {
    "full": "KDDTrain+.txt",
    "20percent": "KDDTrain+_20Percent.txt",
}

NSL_KDD_COLUMNS = [
    "duration", "protocol_type", "service", "flag", "src_bytes", "dst_bytes", "land",
    "wrong_fragment", "urgent", "hot", "num_failed_logins", "logged_in", "num_compromised",
    "root_shell", "su_attempted", "num_root", "num_file_creations", "num_shells",
    "num_access_files", "num_outbound_cmds", "is_host_login", "is_guest_login", "count",
    "srv_count", "serror_rate", "srv_serror_rate", "rerror_rate", "srv_rerror_rate",
    "same_srv_rate", "diff_srv_rate", "srv_diff_host_rate", "dst_host_count",
    "dst_host_srv_count", "dst_host_same_srv_rate", "dst_host_diff_srv_rate",
    "dst_host_same_src_port_rate", "dst_host_srv_diff_host_rate", "dst_host_serror_rate",
    "dst_host_srv_serror_rate", "dst_host_rerror_rate", "dst_host_srv_rerror_rate",
    "attack_type", "difficulty",
]

# IMPORTANT: this is saved to a DIFFERENT directory and DIFFERENT filename
# than scripts/generate_synthetic_tabular.py's output, specifically so the
# two never collide:
#   synthetic generator -> data/raw/tabular/synthetic_traffic.csv
#   this script          -> data/external/tabular/nsl_kdd_mapped.csv
OUTPUT_DIR = Path("data/external/tabular")
OUTPUT_FILENAME = "nsl_kdd_mapped.csv"
RAW_CACHE_FILENAME = "nsl_kdd_raw_cache.txt"


def download_nsl_kdd(subset: str, cache_dir: Path) -> Path:
    """Download the raw NSL-KDD file, caching it locally to avoid re-downloading."""
    cache_dir.mkdir(parents=True, exist_ok=True)
    cache_path = cache_dir / RAW_CACHE_FILENAME

    if cache_path.exists():
        logger.info("Using cached raw file at %s (delete it to force re-download)", cache_path)
        return cache_path

    filename = FILES[subset]
    url = GITHUB_MIRROR_BASE + filename.replace("+", "%2B")
    logger.info("Downloading NSL-KDD (%s) from %s", subset, url)

    response = requests.get(url, timeout=60)
    response.raise_for_status()
    cache_path.write_text(response.text)
    logger.info("Saved raw NSL-KDD file (%d bytes) to %s", len(response.text), cache_path)
    return cache_path


def map_to_honeypot_schema(df: pd.DataFrame) -> pd.DataFrame:
    """
    Map NSL-KDD's 41 connection-level features onto your model's 7-feature
    schema. Each line below states which NSL-KDD field it draws from and why.
    """
    out = pd.DataFrame()

    # src_port / dst_port: NSL-KDD does not record actual port numbers at all
    # (it has protocol_type and service instead, e.g. "tcp"/"http"). There is
    # no honest analog, so these are synthesized as plausible ephemeral/
    # well-known ports rather than left blank -- flagged clearly as such.
    rng = np.random.default_rng(42)
    out["src_port"] = rng.integers(1024, 65535, size=len(df))
    out["dst_port"] = 9999  # constant, matching your honeypot's listening port

    # bytes_received <- src_bytes (bytes sent FROM the source, i.e. what your
    # honeypot would have "received" from the connecting client). NSL-KDD's
    # src_bytes has extreme outliers (some single connections in the billions
    # of bytes), so clip to the same realistic honeypot-scale range your
    # synthetic generator uses (0-1024) rather than passing raw outliers through.
    out["bytes_received"] = df["src_bytes"].clip(0, 1024)

    # connection_duration_ms <- duration (seconds in NSL-KDD) * 1000.
    # NSL-KDD durations go up to ~42,900s (almost 12 hours); clip to a
    # honeypot-realistic upper bound of 5000ms to match your schema's scale.
    out["connection_duration_ms"] = (df["duration"] * 1000).clip(0, 5000)

    # payload_entropy: NSL-KDD has NO byte-level payload at all (it's
    # pre-aggregated flow statistics), so there is no direct source field.
    # As an approximation, we derive a proxy from serror_rate (SYN-error
    # rate) and same_srv_rate: connections with high error rates / low
    # service diversity tend to look like scanning/flooding (low payload
    # entropy in your schema's terms), while "normal"-looking flows get a
    # mid-range entropy value with noise. This is the weakest part of the
    # mapping -- treat any entropy-based result on this dataset with caution.
    base_entropy = 4.0 - (df["serror_rate"] * 3.0) - (df["rerror_rate"] * 1.0)
    noise = rng.normal(0, 0.5, size=len(df))
    out["payload_entropy"] = (base_entropy + noise).clip(0, 8)

    # packet_size <- dst_bytes (response size), same clipping logic as bytes_received.
    out["packet_size"] = df["dst_bytes"].clip(0, 1024)

    # is_repeated_src <- count (# connections to same host in past 2s) > 5,
    # a reasonable proxy for "this source looks like it's reconnecting/
    # repeating", which is conceptually what your honeypot feature measures.
    out["is_repeated_src"] = df["count"] > 5

    # label: NSL-KDD's attack_type column has the literal string "normal"
    # for benign traffic and a specific attack name (e.g. "neptune", "satan")
    # for everything else. Map "normal" -> 0, anything else -> 1, matching
    # your schema's binary label exactly.
    out["label"] = (df["attack_type"] != "normal").astype(int)

    # Keep the original attack_type around as an extra (non-required) column
    # -- useful for your own error analysis (e.g. "which attack categories
    # does the model miss") without affecting predict_proba_from_raw(),
    # which only reads the 7 required columns.
    out["source_attack_type"] = df["attack_type"]

    return out


def validate_mapped_dataset(df: pd.DataFrame) -> None:
    required = [
        "src_port", "dst_port", "bytes_received", "connection_duration_ms",
        "payload_entropy", "packet_size", "is_repeated_src", "label",
    ]
    missing = set(required) - set(df.columns)
    if missing:
        raise ValueError(f"Mapped dataset missing required columns: {missing}")
    if df[required].isnull().any().any():
        raise ValueError("Mapped dataset contains NaN values in required columns.")
    if not set(df["label"].unique()).issubset({0, 1}):
        raise ValueError("Label column is not binary.")
    logger.info("Validation passed: all required columns present, no NaNs, binary label.")


def main():
    parser = argparse.ArgumentParser(
        description="Download NSL-KDD and reshape it to the honeypot 7-feature schema."
    )
    parser.add_argument(
        "--subset", choices=["full", "20percent"], default="20percent",
        help="full = 125,973 rows (~19MB download); 20percent = ~25,000 rows, faster for a quick check.",
    )
    parser.add_argument("--cache-dir", default="data/external/tabular/_raw_cache")
    parser.add_argument("--output-dir", default=str(OUTPUT_DIR))
    args = parser.parse_args()

    cache_dir = Path(args.cache_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    raw_path = download_nsl_kdd(args.subset, cache_dir)
    df_raw = pd.read_csv(raw_path, names=NSL_KDD_COLUMNS)
    logger.info("Loaded %d raw NSL-KDD rows, %d columns", len(df_raw), df_raw.shape[1])

    df_mapped = map_to_honeypot_schema(df_raw)
    validate_mapped_dataset(df_mapped)

    output_path = output_dir / OUTPUT_FILENAME
    df_mapped.to_csv(output_path, index=False)
    logger.info("Saved mapped dataset (%d rows) to %s", len(df_mapped), output_path)

    stats = {
        "source": "NSL-KDD (Tavallaee, Bagheri, Lu, Ghorbani, 2009)",
        "source_mirror": GITHUB_MIRROR_BASE + FILES[args.subset],
        "citation": (
            'M. Tavallaee, E. Bagheri, W. Lu, and A. Ghorbani, '
            '"A Detailed Analysis of the KDD CUP 99 Data Set," '
            'Second IEEE Symposium on Computational Intelligence for '
            'Security and Defense Applications (CISDA), 2009.'
        ),
        "subset": args.subset,
        "n_rows": int(len(df_mapped)),
        "label_distribution": df_mapped["label"].value_counts().to_dict(),
        "note": (
            "Features are an APPROXIMATE mapping from NSL-KDD's connection-level "
            "statistics onto the 7-feature honeypot schema -- not a literal "
            "equivalence. See in-script comments in map_to_honeypot_schema() "
            "for the rationale behind each field."
        ),
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }
    stats_path = output_dir / "nsl_kdd_mapped_stats.json"
    with open(stats_path, "w") as f:
        json.dump(stats, f, indent=2, default=str)
    logger.info("Saved dataset card to %s", stats_path)

    print(f"\n✅ External validation dataset ready: {len(df_mapped)} rows")
    print(f"   Saved to: {output_path}")
    print(f"   (Does NOT overwrite data/raw/tabular/synthetic_traffic.csv)")
    print(f"\nLabel distribution: {df_mapped['label'].value_counts().to_dict()}")


if __name__ == "__main__":
    main()